# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-09 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cartinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='m', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
